### ISSUE TITLE
external packages

### ISSUE THREAD

**Issue by schochastics** [schochastics/graphlayouts#10]
graphlayouts loads `oaqc` and `gbp` but only needs one function from each package. It might be good to implement these algorithms in graphlayouts to get rid of these dependencies

**Comment by thomasp85** [comment]
I would very much like this. The current dependencies means I can't really import graphlayouts in ggraph... Especially rgl (from gdb) is quite heavy

**Comment by schochastics** [comment]
Yes gdb is way to heavy as a dependency. Especially since I only need one function. However, I have not yet managed to implement the bin packing algorithm myself. I am contemplating of reverting back to the circular drawing of components. I am not sure how much the rectangular layout of components is appreciated anyway

**Comment by thomasp85** [comment]
If it is only for that I’d consider removing it until you have time to find a less dependency heavy solution...

I’ve seen some rectangle packing algorithms with D3 somewhere. Don’t know if they could be used

**Comment by schochastics** [comment]
problem solved! Turns out we don't need sophisticated bin packing. I just implemented a very naive one myself which should be enough for networks. Extreme graph example below:
![example](https://user-images.githubusercontent.com/17147355/63178896-d8d93980-c042-11e9-9586-5039de200a61.png)

**Comment by thomasp85** [comment]
Great. It might makes sense to start with the largest subgraph and place smaller ones around that though to avoid the unbalanced feel. Don’t know if that makes sense...

In any case this is def good enough to let gbp go

**Comment by schochastics** [comment]
I think it is easier to parse all components at once to compare them with this layout.  This is highly subjective but for academic purposes I'd prefer the above but from a design point of view you are probably right.

**Comment by thomasp85** [comment]
I’ll let you be in control of that

**Comment by schochastics** [comment]
@thomasp85 I am afraid that getting rid of oaqc is a hairy business. It is only necessary for `layout_as_backbone` function, so I could at least move it to suggested packages. How does that sound?The alternative is I implement a less efficient version of the needed algorithm.

**Comment by thomasp85** [comment]
oaqc is not as big of a problem as it doesn’t have any hard dependencies. The biggest issue is the dependency on R 3.4 which is still not that old. If you can move it to suggest I think it would be good

**Comment by schochastics** [comment]
all right oaqc is going to suggest. Never really thought about the R version. Is there a way to check the package on, say R 2.10?

**Comment by thomasp85** [comment]
I think Roger Peng has made docker images for most old version but honestly that would be overkill. At RStudio we promise that our package works on 4 year old versions of R meaning we currently support down to 3.2

**Comment by thomasp85** [comment]
If they’ve added the version requirement just because that was the version when they developed it, and they could be convinced to loosen it I think it could stay in import but I wouldn’t know if they’d be interested in that (or if it is possible)

**Comment by schochastics** [comment]
I can easily lower the R dependency of graphlayouts to 3.2. I am fine with leaving oaqc as suggest, given that it really is only needed for one function. 

The authors of oaqc are old colleagues of mine so I could ask them about it. However, the main developer moved on from academia to the private sector and I am not sure how willing he still is to put work in that package, given that it is finalized and doesn't need development anymore.
