### ISSUE TITLE
layout_as_backbone --> crash!

### ISSUE THREAD

**Issue by timonelmer** [schochastics/graphlayouts#14]
Grüezi David! I was so excited to finally be able to use a backbone layout in R directly (and not via the visone GUI). But when I want to use it for one particular network R crashes. 

you can download the example data here: https://polybox.ethz.ch/index.php/s/v8nv7jbMpGfhbUs

````
rm(list = ls())
library(igraph)
library(ggraph)
library(graphlayouts)

set.seed(23)
know.g <- erdos.renyi.game(80, p.or.m = 0.005379747) 
bb <- layout_as_backbone
(know.g) # works fine

load("know_for_david.RData")
know.g <- graph.adjacency(know)
bb <- layout_as_backbone(know.g) # crash!
````

Peace!

**Comment by schochastics** [comment]
Grüezi Timon,

You created a directed graph. the backbone layout only works with undirected ones. See code below

```
load("know_for_david.RData")
know.g <- graph.adjacency(know,mode = "undirected")
```
Also, the graph you send me is not connected (you can get a quick overview with `qgraph(know.g)`.
The backbone layout only works with connected graphs. 
Hope this helps in your plotting endeavors!

**Comment by timonelmer** [comment]
makes sense!

Merci 👍:)
