### ISSUE TITLE
Can I steal qgraph?

### ISSUE THREAD

**Issue by thomasp85** [schochastics/graphlayouts#19]
I currently have `nplot()` in ggraph for similar, but more general, functionality. `qgraph` is a much better name though...

So a gentle request if we can come to an agreement🙂. If you don’t want to it is fine of course

**Comment by schochastics** [comment]
Go ahead and take it! I just implemented it since it was missing in ggraph. I was only waiting for you to ask this question :-)

**Comment by thomasp85** [comment]
qgraph is now part of ggraph (though with different internals)
