### ISSUE TITLE
Better error message for backbone layout

### ISSUE THREAD

**Issue by thomasp85** [schochastics/graphlayouts#24]
I get a rather uninformative error when I try to use the backbone layout with the `'meredith'` graph. I cannot parse whether it is a bug in the layout code or if the graph type is somehow unsupported

```r
ggraph(create_notable('meredith'), 'backbone') + 
geom_edge_link()
#>  Error in reweighting(el - 1, N_ranks) : Not a matrix. 
```

**Comment by schochastics** [comment]
This appeared to be a bug when some edges are not part of any C4. Should be fixed now
