### ISSUE TITLE
Return distance as part of focus layout output

### ISSUE THREAD

**Issue by thomasp85** [schochastics/graphlayouts#27]
Id' like to add the used distance in the focal layout as part of the ggraph layout. I could calculate it in ggraph, but that would basically be a repeat of one of the calculations in the layout algorithm. Could this measure be returned along with the coordinates by the algorithm?

**Comment by schochastics** [comment]
Is it ok to do that with a list, similar to the layout_as_backbone?
`return(list(xy=coords,distances=D))`

**Comment by thomasp85** [comment]
That is up to you. It would be a breaking change, but OTOH more consistent

**Comment by schochastics** [comment]
all right, a list it is!

**Comment by schochastics** [comment]
returning the complete distance matrix is of course bogus. Only the distances to the focus should be included

**Comment by schochastics** [comment]
@thomasp85 `layout_with_focus` now returns a list of coordinates and the distances to the focus node. I also added a weights parameter. I promise this was the last change in code before submission

**Comment by thomasp85** [comment]
yes, returning only the distance to the focus is what I expected... I also thought about requesting a weights argument so that addition is welcome :-)
