### ISSUE TITLE
Use edge weight for backbone layout

### ISSUE THREAD

**Issue by ArlindNocaj** [schochastics/graphlayouts#33]
Great work David, 

thnx a lot for providing this packages.

Is there also a way to use a specific edge weight for the backbone layout?

**Comment by schochastics** [comment]
@ArlindNocaj The backbone layout is defined with the quad census of Mark, so I assume there is no way to include edge weights during the calculation? Or am I missing something?

**Comment by ArlindNocaj** [comment]
You can replace the edge weight just before you sort and use union MST. Of
course it will not use the original backbone weight then, but if you have
already a good similarity that might be better depending on the use case.


David Schoch <notifications@github.com> schrieb am Mo. 4. Mai 2020 um 17:13:

**Comment by schochastics** [comment]
ah I think I get it. you mean calculate the union MST with a custom edge weight instead of the backbone weights, right? So far thats not possible, but I'll think about it for the next version

**Comment by ArlindNocaj** [comment]
Yes exactly. Thats often very usefull when you have similarity measure
given, eg similarity graph.


David Schoch <notifications@github.com> schrieb am Mi. 6. Mai 2020 um 15:23:
