### ISSUE TITLE
layout_as_multilevel only for two levels?

### ISSUE THREAD

**Issue by jaspershen** [schochastics/graphlayouts#38]
Thanks for your amazing packages for network layout. I have a question that if layout_as_multilevel only for two levels? Thank you.

**Comment by schochastics** [comment]
Thanks! Yes the layout only works for two levels. It is also not that straightforward to extend to more than two. If you have ideas feel free to share them :)

**Comment by jaspershen** [comment]
Thank you very much for your quick reply. Sure, I can try to achieve it based on your amazing function if it is possible. Thanks again.
