### ISSUE TITLE
Resource allocation and tuning

### ISSUE THREAD

**Issue by alopezespino** [schochastics/graphlayouts#43]
Hi, I am running this package in an HPC. Particularly, the layout_as_backbone function. I can allocate as many as five nodes, with 20 processors and 12GB for each processor. 

Could you give me a better sense of whether it is possible to allocate such resources so that the layout is computed faster? I guess there is no way to run a multi-node application but how about multiple cores? Or is the best way just to allocate a lot of RAM to a single core?

Thanks in advance for your guidance!

**Comment by schochastics** [comment]
Hi,
The implementation is unfortunately not made for parallel computing. So the best you can do is allocate a lot of RAM to a single core.

**Comment by alopezespino** [comment]
I see. This is anyways helpful. Thanks!
