### ISSUE TITLE
layout_as_backbone - returns data with one node less

### ISSUE THREAD

**Issue by avladimirova** [schochastics/graphlayouts#44]
I have run
`bb <- layout_as_backbone(g, keep = 0.4)`
and got `bb$xy` where one node is missing but I can understand which one and what to do with my data to solve the issue.
Seems this node lost in `umst <- function(g)`.
There is nothing about this issue in `??layout_as_backbone`, is it possible to identify the node lost?

Thank you in advance!

**Comment by schochastics** [comment]
could you provide a reproducible example? I cannot replicate the error with a random network
``` r
library(igraph)
library(graphlayouts)

set.seed(123)
g <- sample_gnp(100,0.2)
bb <- layout_as_backbone(g,keep=0.4)
nrow(bb$xy)==vcount(g)
#> [1] TRUE
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by avladimirova** [comment]
Sure, I am also very interested to know what went wrong with this network. I have attached `bb_issue.RData` with graph `g` and returned list `bb`. Maybe it will be a useful note that the function works well with other graphs
[bb_issue.zip](https://github.com/schochastics/graphlayouts/files/9302683/bb_issue.zip)
.

**Comment by schochastics** [comment]
Thanks. 
I don't know what exactly the problem is, but I am sure it is caused by the fact that the graph is disconnected. I'd recommend that you only calculate the backbone on the biggest component.

```r
 comps <- igraph::components(g,mode = "weak")
 g <- igraph::induced_subgraph(g,which(comps$membership==which.max(comps$csize)))
```

In the next version, I will add a warning to the function if it is applied to a disconnected graph (but of course will still look for what causes the issue)

**Comment by avladimirova** [comment]
Thank you, will do so. But I think multiple components is not the reason. I used this function for a graph with a bunch of isolates and it worked fine.

**Comment by schochastics** [comment]
Did some testing and also didn't get any missing nodes. Really weird problem. Will definitely investigate this further

**Comment by schochastics** [comment]
Ok found the issue. The problem occurs when the isolates are the last vertices in the graph (that is the vertices with the highest ids). In your example, node 129 is an isolates and thus gets "lost".

``` r
library(igraph)
library(graphlayouts)

g1 <- sample_gnp(20,0.4)
g2 <- graph.empty(5,directed=FALSE)
#isolates come first
nrow(layout_as_backbone(g2+g1)$xy)==(vcount(g1)+vcount(g2))
#> [1] TRUE
#isolates come last
nrow(layout_as_backbone(g1+g2)$xy)==(vcount(g1)+vcount(g2))
#> [1] FALSE
```

**Comment by avladimirova** [comment]
Great, thank you so much! I really like your package and the tutorials are very helpful! 
P.S. A small user feedback: it would be ideal if `bb` also has vertexes names.

**Comment by schochastics** [comment]
Thanks, I look into the vertex names later. This might interfere with the connection to `ggraph`.
