### ISSUE TITLE
Stress layout fails for disconnected graphs with an explicit weights vector

### ISSUE THREAD

**Issue by arcresu** [schochastics/graphlayouts#47]
The stress majorisation layout doesn't seem to expect the graph to be disconnected when a weights vector is provided. Here's an example disconnected graph with 4 edges where a weights vector of 4 elements causes a length mismatch error:

``` r
g <- igraph::graph_from_literal(A-B-C-A, D-E)
igraph::ecount(g)
#> [1] 4
graphlayouts::layout_with_stress(g)
#>          [,1]      [,2]
#> [1,] 2.970066 0.2428427
#> [2,] 2.000000 0.0000000
#> [3,] 2.274725 0.9615229
#> [4,] 0.000000 0.0000000
#> [5,] 1.000000 0.0000000
graphlayouts::layout_with_stress(g, weights = c(1, 1, 1, 1))
#> Error in igraph::distances(sg, weights = weights): At core/paths/dijkstra.c:116 : Weight vector length does not match, Invalid value
```

<sup>Created on 2022-10-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup> 

The layout implementation contains a loop over connected components of the graph. For each component, an induced subgraph `sg` is created. It then calls `igraph::distances()` with the subgraph, but provides the full weights vector of the original graph:
https://github.com/schochastics/graphlayouts/blob/5ddc5e3f945b24f26d19c9d144fcbf0c779ac64a/R/layout_stress.R#L67

If I'm understanding this correctly, the weights passed here should be a subset of the weights vector with elements corresponding only to the vertices retained in the subgraph for that component.

**Comment by schochastics** [comment]
Thanks for pointing this out. Should be fixed in the dev version now
