### ISSUE TITLE
ARMA_64BIT_WORD should be used conditionally, apparently

### ISSUE THREAD

**Issue by barracuda156** [schochastics/graphlayouts#49]
Source code forces `ARMA_64BIT_WORD=1`, a define which seems to be specific to 64-bit platforms. If so, it should be used conditionally.

**Comment by schochastics** [comment]
I believe this has nothing to do with 32-bit/64-bit platforms. It just allows RcppArmadillo to work with very large matrices.
But happy to be corrected here. I just followed [stackoverflow](https://stackoverflow.com/questions/40592054/large-matrices-in-rcpparmadillo-via-the-arma-64bit-word-define)

**Comment by barracuda156** [comment]
@schochastics I made a conclusion based on the following statement, however it is not decisive:
> Use 64 bit integers. Automatically enabled when using a 64-bit platform, except when using Armadillo in the R environment (via RcppArmadillo).

https://arma.sourceforge.net/docs.html
I guess I should just try running examples with 64bit_word defined and see if it works on 32-bit arch or breaks down.

**Comment by schochastics** [comment]
Please do and let me know if something breaks. If so, I will add a fix

**Comment by barracuda156** [comment]
> Please do and let me know if something breaks. If so, I will add a fix

@schochastics I think you are right: compilation works on 32-bit with `ARMA_64BIT_WORD` being left in place, and tests pass. (Though tests pass without it too.)

Is there a specific test to run with your package which would use very large matrices?

**Comment by schochastics** [comment]
The only case where this becomes necessary is for very large graphs when using `layout_with_sparse_stress()` . You can try graphs from here: https://sparse.tamu.edu/
