### ISSUE TITLE
ggplot2 warning when running README example

### ISSUE THREAD

**Issue by bpbond** [schochastics/graphlayouts#51]
Running the first example in the README produces a warning from ggplot2:

```r
> ggraph(pa,layout = "nicely")+
+     geom_edge_link0(width=0.2,colour="grey")+
+     geom_node_point(col="black",size=0.3)+
+     theme_graph()
Warning message:
Using the `size` aesthetic in this geom was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` in the `default_aes` field and elsewhere instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated. 
```

Noted as part of https://github.com/openjournals/joss-reviews/issues/5238

**Comment by bpbond** [comment]
(I recognize this is being generated by `ggraph::ggraph`, not this package, just logging it.)

**Comment by schochastics** [comment]
Yes this is a long standing issue of `ggraph` because of changes of `ggplot2`. Feel free to reopen but I close this here, given that it is an independent issue
