### ISSUE TITLE
README example error: oaqc needed

### ISSUE THREAD

**Issue by bpbond** [schochastics/graphlayouts#52]
The example that begins with 
```r
bb <- layout_as_backbone(g,keep=0.4)
```
produces an error:
```
Error: oaqc is needed for this function to work. Please install it.
```
This isn't very clear. I assume that `oaqc` is a package, and available on CRAN? Is there a reason it's not listed in the package DESCRIPTION file under `Suggests:` or `Imports:`?

Noted as part of https://github.com/openjournals/joss-reviews/issues/5238

**Comment by schochastics** [comment]
hmm it is part of the DESCRIPTION file: https://github.com/schochastics/graphlayouts/blob/298ee887f6ddbf52b96fc009a7a0e9ae47337c05/DESCRIPTION#L19

I added the installation to the README

**Comment by bpbond** [comment]
Ah, sorry I missed that! Thanks.
