### ISSUE TITLE
dynamic layouts example

### ISSUE THREAD

**Issue by bpbond** [schochastics/graphlayouts#54]
The "dynamic layouts" example in the README begins
```r
#gList is a list of longitudinal networks.

xy <- layout_as_dynamic(gList,alpha = 0.2)
pList <- vector("list",length(gList))
```

This is unclear; where does `gList` come from? Is there a way to make this example reproducible?

Noted as part of https://github.com/openjournals/joss-reviews/issues/5238

**Comment by schochastics** [comment]
@bpbond can you check if it is reproducible for you now?

**Comment by bpbond** [comment]
Definitely. Thanks for the changes!
