### ISSUE TITLE
Vignette?

### ISSUE THREAD

**Issue by bpbond** [schochastics/graphlayouts#58]
Is there a reason that https://www.mr.schochastics.net/material/netVizR/ couldn't become a built-in vignette? This would provide a more natural resource for R users.

Noted as part of https://github.com/openjournals/joss-reviews/issues/5238

**Comment by schochastics** [comment]
True. It is far too long though in my opinion for a vignette. Will think how I can include a condensed version somehow

**Comment by schochastics** [comment]
I added a rudimentary vignette which introduces the main layout algorithm and points to the online tutorial. The tutorial depends on too many packages which I would need to add to the package. Hence the very boiled down version

**Comment by bpbond** [comment]
```r
> devtools::install_github("schochastics/graphlayouts")
> library(graphlayouts)
> vignette(package="graphlayouts")
no vignettes found
```

Hmm. I looked through the [vignette Rmarkdown file](https://github.com/schochastics/graphlayouts/blob/main/vignettes/graphlayouts.Rmd) and it looks great but not sure why it's not visible when I install as above. Anyway, closing as addressed—thanks!—but please double-check it's available to users.
