### ISSUE TITLE
Paper/Statement of need: other network packages

### ISSUE THREAD

**Issue by ndjackso** [schochastics/graphlayouts#61]
Issue related to [openjournals/joss-reviews#5238](https://github.com/openjournals/joss-reviews/issues/5238)

**Comment by schochastics** [comment]
>The “Statement of Need” section makes reference to igragh and ggraph but there could be an expansion of content to situate graphlayouts relative to current static (e.g., network, sna, statnet, etc.) and dynamic (e.g., networkD3 and VizNetwork) network visualization packages in R.

Thanks for the suggestion! I included those packages in the statement of need
