### ISSUE TITLE
Paper/Use for plotting: section necessary

### ISSUE THREAD

**Issue by ndjackso** [schochastics/graphlayouts#62]
Issue related to [openjournals/joss-reviews#5238](https://github.com/openjournals/joss-reviews/issues/5238)

**Comment by schochastics** [comment]
> The “Use for plotting” section may be redundant as the plotting capabilities are demonstrated in the subsequent sections and code. Consider removing this section or add additional content to distinguish it further from the other sections

agreed and was deleted
