### ISSUE TITLE
Paper/Overview of algorithms: more details

### ISSUE THREAD

**Issue by ndjackso** [schochastics/graphlayouts#63]
Issue related to [openjournals/joss-reviews#5238](https://github.com/openjournals/joss-reviews/issues/5238)

**Comment by schochastics** [comment]
> The “Overview of algorithms” section shows some of the visualization functions but the descriptions are minimal. There is also unequal coverage of the algorithms presented in the Github repo. Consider adding more detail for all algorithms.

This is indeed a good point. My decision to keep it minimal are guided by the journals guidelines. The paper is not supposed to have a tutorial character. This is why I opted for only shortly presenting the important algorithms. I clarified this a bit more now at the beginning of the section and explicitly point to more detailed resources (also on github)

**Comment by ndjackso** [comment]
The additional text and links to other resources are good. Thank you for adding this content.
