### ISSUE TITLE
Multi-level layout for graph with disconnected components

### ISSUE THREAD

**Issue by lilianemanny** [schochastics/graphlayouts#69]
Hi, I have been using your graphlayouts package several times before. At the moment, I am trying to use the function _layout_igraph_multilevel_  for a graph with disconnected components but it seems like this is not supported. Is there any way to visualize a bipartite not fully connected graph (the majority is connected but there are several small disconnected parts) in a multilevel layout? Thanks a lot for your help!

**Comment by schochastics** [comment]
Yes the support of disconnected graphs is a long standing issue (see #48). 
Here is a workaround using some igraph functions. Hope this helps

``` r
library(ggraph)
library(graphlayouts)
library(igraph)

set.seed(1234)
g <- sample_bipartite(n1 = 50,n2 = 50,p = 0.1)
h <- sample_bipartite(n1 = 10,n2 = 10,p = 0.3)
l <- g + h
V(l)$lvl <- V(l)$type+1
xy <- layout_components(l,layout_as_multilevel,type="all")

ggraph(l,"manual",x=xy[,1],y=xy[,2]) + 
    geom_edge_link0(edge_color="grey66",edge_alpha=0.4) +
    geom_node_point(aes(color=as.factor(lvl)))
```

![](https://i.imgur.com/kT3Naqr.png)

<sup>Created on 2023-05-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lilianemanny** [comment]
Thank you for this quick help!
